### ISSUE TITLE
formatação da tabela no enunciado das questões

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#16]
A formatação das tabelas no enunciado das questões não está funcionando. É preciso um css padrão para tabelas no enunciado

**Comment by Lobz** [comment]
Tem um exemplo de exercício criado que eu possa usar para acertar isso?

**Comment by adalardo** [comment]
102.03 Conta de luz (http://notar.ib.usp.br/exercicio/4)
103.02 Criação de um data frame
107.01 Altura na Infância e Na Vida Adulta
201.4 Independente ou agregado? 
203.2 Sobrevivência de árvores 
203.3 Comparando intervalos de verossimilhança

**Comment by andrechalom** [comment]
Isso pode ser resolvido com um editor WYSIWYG na criação dos exercícios. Vou abrir um issue pra issue e linkar com este.
