### ISSUE TITLE
Apagar uma turma

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#17]
É importante poder deletar a turma toda. Por exemplo, criei uma turma (Turma da Mônica) para testar a plataforma e agora não consigo apagar ...

**Comment by Lobz** [comment]
Certo. Atualmente a turma só pode ser apagada depois de removidos todos os prazos e alunos. Só para esclarecer, o que você está pedindo é um botão que faça tudo isso com um clique só?

**Comment by adalardo** [comment]
Sim, isso! Algumas turmas são grandes e ter que tirar os usuário da turma, um por um, demora.
