### ISSUE TITLE
Deletar usuário com erro

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#21]
Ao tentar deletar um usuário pela aba de  editar usuários, ao clicar em deletar aparece uma mensagem de alerta que a ação não pode ser desfeita e, ao clicar em ok aparece a página de erro 500. Ao final o usuário não é deletado

**Comment by Lobz** [comment]
Acho que sei o que está acontecendo. O sistema não consegue deletar um usuário que pertença a uma turma. Precisarei impletentar uma rotina que remove o aluno de todas as turmas antes da deleção. Obrigado pelo bug report.

**Comment by adalardo** [comment]
Não é possível também editar usuários pertencente a alguma turma (erro 500 tb!)
