### ISSUE TITLE
Remoção de usuário de turma fica processando indefinidamente

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#22]
A remoção de usuário da turma está funcionando, mas fica processando até clicar em outro link da página

**Comment by Lobz** [comment]
Não estou conseguindo reproduzir este erro. Qual browser vocë está usando? E está usando o botão de remocção da página da trma, da página de edição da turma, ou da página de edição do usuário?

**Comment by adalardo** [comment]
Botão "Remover" da sessão "Membros" na página de edição da "Turma", removendo usuário apenas da Turma. No navegador Firefox fica processando até mudar de página,  testei no Chromium e funcionou bem, sem problemas...

**Comment by Lobz** [comment]
Não consegui reproduzir esse problema. Estou fechando esse issue. Se continuar a ocorrer, por favor reabra com o máximo de detalhes.
