### ISSUE TITLE
Lista de Exercícios fora de ordem

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#26]
Listas de exercícios dentro das turmas depois de cadastrados, nas abas "Prazos Futuros" e "Prazos Passados" não aparecem em ordem (http://notar.ib.usp.br/turma/3). O ideal que sejam indexados pelo dia e horário e em seguida por ordem alfanumérico.  O mesmo para a lista do  usuário no "Meu perfil"  nos tópicos "Prazos Futuros" e "Notas Passadas"

**Comment by Lobz** [comment]
Realmente eu não havia considerado o problema de muitos exercícios terem a mesma data de entrega.

**Comment by Lobz** [comment]
resolvido
