### ISSUE TITLE
Erro “500|Server error” ao postar exercício enviando como arquivo

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#27]
Exercício funciona com o código postado diretamente na caixa "Escreva seu código aqui" mas não quando enviado como arquivo. Descobrimos que comentários no arquivo de código gera erro 500 em vários, se não todos os exercícios.

**Comment by Lobz** [comment]
Isso ocorre quando o arquivo contém caracteres especiais

**Comment by Lobz** [comment]
erro só ocorre com usuário logado - erro na conexão com o database?
