### ISSUE TITLE
Mensagem de alerta quando nota não ficará salva

### ISSUE THREAD

**Issue by Auler-J** [lageIBUSP/notaR#29]
Quando o aluno não está logado a mensagem "ATENÇÃO: você não está logado. Sua nota não será gravada." aparece logo abaixo da caixa de enunciado. Ficaria mais visível caso aparecesse logo antes da caixa com a nota do exercício.

Quando o exercício é enviado fora de prazo, nenhuma mensagem de alerta é enviada. Seria bom que, quando isso ocorresse, uma mensagem nos mesmos moldes da anterior fosse enviada. "ATENÇÃO: O prazo máximo para esse exercício foi em [data]. Sua nota não será gravada."

**Comment by Lobz** [comment]
closed by #50
