### ISSUE TITLE
Tela amigável de erro 500

### ISSUE THREAD

**Issue by Lobz** [lageIBUSP/notaR#40]

**Comment by Lobz** [comment]
Pra falar a verdade eu não tenho certeza do que queremos.

**Comment by Lobz** [comment]
@andrechalom @adalardo o que a página de erro 500 deve dizer?

**Comment by andrechalom** [comment]
Coisas importantes pra mim:
- avisar ao usuário que ocorreu um erro, e que isso não é culpa dele.
- dar uma instrução de como proceder (recarregar a página provavelmente não vai adiantar se for um crash do código PHP, mas ele pode entrar em contato com um admin ou tentar novamente mais tarde?)
- um link para a homepage (torcendo para a homepage não ter morrido com erro 500 tbm)
- evitar termos técnicos (o usuário provavelmente não sabe a diferença entre um erro 404 ou um erro 500)

Se tivermos alguma ferramenta de monitoramento (p. ex. Google Analytics) é importante q essa ferramenta consiga reportar acessos de erro 500

**Comment by andrechalom** [comment]
Tela antiga quando ocorre um erro 404:
![unnamed](https://github.com/lageIBUSP/notaR/assets/1994997/6f638c7a-8660-4c02-8355-d6a32e4a1a16)
Tela nova (com identidade visual preservada, descrição do problema e um passo a passo que o usuário pode seguir:
![unnamed](https://github.com/lageIBUSP/notaR/assets/1994997/48f6301e-950c-47d1-9a14-22cc38568c7f)
