### ISSUE TITLE
Testar instalação do sistema notaR em Windows

### ISSUE THREAD

**Issue by Lobz** [lageIBUSP/notaR#55]

**Comment by Lobz** [comment]
Tentei instalar no windows 10 Pro. É bem chatinho, ja q o docker foi feito pra servidores linux. Isto é realmente necessário? Quem vai realmente querer instalar em windows?

No momento estou batendo num erro no qual o conteiner do app fecha com erro `/usr/bin/env: 'bash\r': No such file or directory`

**Comment by andrechalom** [comment]
Resolvido e documentado em https://github.com/lageIBUSP/notaR/wiki/Como-instalar-o-seu-pr%C3%B3prio-notaR
