### ISSUE TITLE
Edição de erro nos testes lógicos

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#62]
Quando há alguma inconsistência em alguns dos testes lógicos da correção do exercício, a plataforma aponta corretamente em que linha está o  erro. Entretanto, não permite a edição da condição ou peso. Ela tem que ser deletada e reconstruída.  Por exemplo, quando não se coloca o peso de alguma condição, a plataforme reconhece o erro e indica que o peso é obrigatório, entretanto, não é possível incluir o peso na condição  em questão e simplesmente corrigir. É necessário deletar toda a linha da condição e refaze-la.

**Comment by Lobz** [comment]
Oi, não consegui reproduzir esse erro, pode me mandar mais detalhes? Tem um exercício de teste em que isso sempre aconteça? É na criação ou na edição? Talvez um screenshot ajude.

**Comment by adalardo** [comment]
Salve algum exercício sem colocar algum peso em um condição. Isso gera erro. Ao voltar à edição do exercício, ele não permite a inclusão do peso, a menos que se delete a linha da condição e faça ela de novo.

**Comment by Lobz** [comment]
Ok. O que acontece se você clica na caixinha de texto? Pra mim, dás pra escrever normal, veja:
![image](https://user-images.githubusercontent.com/1750256/170118514-8969c137-39f4-467a-a4b8-5bdd21e1c23d.png)

Talvez tenha um problema no tamanho da caixa, que parece estar menor pra você, e aí o símbolo de ! está escondendo o que você escreve. Isso já aconteceu antes e corrigimos só aumentando o tamanho da caixa, mas se o tamanho está flexível, talvez seja melhor descobrir como remover esse símbolo

**Comment by adalardo** [comment]
Continuo sem conseguir editar o campo de pesos quando há algum erro no Chromium. No firefox não consigo visualizar o número que está sendo inserido, mas ele é incluído no campo.

**Comment by Lobz** [comment]
não vamos garantir funcionalidade no chromium. vou fechar este issue por enquanto, se mais pessoas tiverem problema reabrimos
