### ISSUE TITLE
Funções proibidas em exercícios 

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#63]
Quando uma função é indicada como proibida, p.ex. proibir("dev.off"), o teste lógico de proibidas() acusa o uso da função se ela for usada nas pré-condições ou nos testes lógicos. Este é um comportamento indesejado, pois podemos impedir o usuário de usar uma função no seu código, por questões didáticas, mas ao mesmo tempo precisamos da função para a correção do exercício.
Além disso, na documentação do "proibir" seria importante dizer que o nome da função deve ser entre "" e se é possível submeter vários nomes de funções em um único vetor como: proibir(c("dev.off", "x11", "X11", "png")). A vetorização da ação da função seria desejável.

**Comment by adalardo** [comment]
para resolver o problema pode apenas indicar o caminho completo da funcao como por exemplo: "grDevices::.devUp"

**Comment by Lobz** [comment]
vou fechar isso aqui e substituir por dois issues mais focados
