### ISSUE TITLE
Arquivos de dados e figuras não fazem o download

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#64]
Na janela de gerenciamento de arquivos não é possível baixar os arquivos do notaR. Apesar dos arquivos estarem sendo copiados para a área de trabalho da sessão do R, não estou conseguindo baixar ou fazer o link dos arquivos nos enunciados.

**Comment by adalardo** [comment]
ATUALIZAÇÃO DO PROBLEMA: quando clica no nome do arquivo na janela de gerenciamento de arquivos, o arquivo abre em uma nova aba, mas demora MUITO, por isso achei que não estava baixando.  A transição entre o endereço do lararvel no formato: "http://notar.ib.usp.br/arquivo/1" para "http://notar.ib.usp.br//storage/arquivos/alunos2018.txt" é muito lento demora minutos para acontecer.  Estou conseguindo acessar os arquivos rapidamente usando o caminho "/storage/arquivos/"

**Comment by Lobz** [comment]
Pode enviar um link de exemplo? O arquivo 1 em particular tem apenas uma linha e carrega rapidamente.

É possível mudar a forma de oferecimento desses arquivos para criar um link de download, em vez de abrir em nova aba. Você acha que isso seria melhor?

**Comment by adalardo** [comment]
O exemplo de link é esse mesmo. Agora aqui está intermitente. Esta dando problema no firefox e parou de dar problema no chromium (mas tinha dado antes de abrir esse issue!).  O firefox chegou a funcionar, fechei ele e abri novamente e ele continuou a dar problema. Limpei historico e tudo mais,  mas continua dando problema.
![erroArquivo](https://user-images.githubusercontent.com/7620725/170304033-fea4a6dc-d51f-4bdc-af58-e86b251960e8.png)

Fica assim assim, muitos minutos...
