### ISSUE TITLE
Page Expire 419

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#75]
Ao editar uma página de exercícios por muito tempo, ela  expira por falta de atividade. Além de ser dificil voltar a página de login  (não funciona atualizar nem voltar o histórico de navegação)  é preciso digitar a página inicial do notaR  de novo na barra de endereço para acessar a página de login novamente. **Toda a edição feita é perdida**. Um comportamento desejável é que ao tentar salvar uma página que expirou, o notaR leva a página de login e em seguida retorne a página em edição usando o cache do navegador...

**Comment by Lobz** [comment]
Quando a página expira, recarregar a página com F5 ou Ctrl+R é suficiente para restaurar a sessão. Não precisa refazer o login.

Em todo caso, aumentei o tempo da sessão de 2h para 24h. Reabra o issue se o problema persistir.
