### ISSUE TITLE
Cálculo de nota

### ISSUE THREAD

**Issue by adalardo** [lageIBUSP/notaR#77]
Tenho notado alguma inconsistência na nota do exercício 106.04 ANOVA fácil! A solução do exercício é:

```
ndias <- c(10, 12, 12, 13, 9, 11, 11, 12, 12, 13, 15, 16)
irriga <- factor(rep(c("C", "B", "A"), each = 4), levels = c("C", "B", "A"))
flor <- data.frame(ndias, irriga)
aovFlor <- aov(ndias ~ irriga)
summaryFlor <- summary(aovFlor)
anovaFlor <- anova(aovFlor)

```
Quando faço o teste comentando a última linha, o valor de correção é 58.3% e pelas minhas contas deveria ser 79.2% da mesma forma que quando comento a penultima linha
![ex106_02nota02](https://user-images.githubusercontent.com/7620725/174272913-bb2bdf6c-2b2a-4f42-9911-508ae7355102.png)
![ex106_02nota01](https://user-images.githubusercontent.com/7620725/174272958-f481d708-b8c5-4c5e-b823-5764367bb91c.png)

**Comment by andrechalom** [comment]
Alê, o cálculo de nota é o mesmo código, exatamente inalterado, desde 2013. Essa funcionalidade foi testada exaustivamente por quase dez anos. Não é razoável que isso ainda esteja em discussão.

No exercício que você citou, existem 2 testes idênticos: o teste 6 e o teste 8, ambos com peso 5, validam o objeto `anovaFlor`. Removendo esse problema do exercício, as duas falhas levam à mesma nota, 73.7%.

![image](https://user-images.githubusercontent.com/1994997/174459345-5acd2207-f6ba-4de3-9625-70feff35eb6e.png)

![image](https://user-images.githubusercontent.com/1994997/174459323-cc78a220-edf0-42a1-9b83-a375a9c2ce15.png)

Entendo que o notaR é um projeto colaborativo e abrir issues no Github é importante para dar visibilidade aos problemas, mas por favor, antes de criar um issue, certifique-se de que a questão que você está levantando é realmente um problema da plataforma e não do conteúdo do exercício. O conteúdo do exercício não é e não deve ser responsabilidade do time de desenvolvimento da plataforma.
